version: '3'
services:
  mongo1:
    image: mongo:4.2.6
#    ports:
#      - "27020:27020"
    volumes:
      - $PWD/storage/db/mongo1:/data/db
      - $PWD/storage/log/mongo1:/var/log/mongodb
#    networks:
#      - mongo-networks
    network_mode: host
    command: mongod --bind_ip 0.0.0.0 --port 27017 -replSet replication
  mongo2:
    image: mongo:4.2.6
#    ports:
#      - "27020:27020"
    volumes:
      - $PWD/storage/db/mongo2:/data/db
      - $PWD/storage/log/mongo2:/var/log/mongodb
#    networks:
#      - mongo-networks
    network_mode: host
    command: mongod --bind_ip 0.0.0.0 --port 27021 --replSet replication
  mongo3:
    image: mongo:4.2.6
#    ports:
#      - "27020:27020"
    volumes:
      - $PWD/storage/db/mongo3:/data/db
      - $PWD/storage/log/mongo3:/var/log/mongodb
#    networks:
#      - mongo-networks
    network_mode: host
    command: mongod --bind_ip 0.0.0.0 --port 27022 --replSet replication
